-- Script generated by Lokasenna's GUI Builder

local lib_path = reaper.GetExtState("Lokasenna_GUI", "lib_path_v2")
if not lib_path or lib_path == "" then
    reaper.MB("Couldn't load the Lokasenna_GUI library. Please run 'Set Lokasenna_GUI v2 library path.lua' in the Lokasenna_GUI folder.", "Whoops!", 0)
    return
end
loadfile(lib_path .. "Core.lua")()


GUI.req("Classes/Class - Label.lua")()
GUI.req("Classes/Class - Button.lua")()
GUI.req("Classes/Class - Textbox.lua")()
GUI.req("Classes/Class - Slider.lua")()
-- If any of the requested libraries weren't found, abort the script.
if missing_lib then return 0 end

GUI.name = "Electric Car"
GUI.x, GUI.y, GUI.w, GUI.h = 0, 0, 605, 225
GUI.anchor, GUI.corner = "mouse", "C"

velocity = 0
minVelocity = 0
maxVelocity = 60
isAccelerating = false
isBraking = false

function updateVelocity(newVelocity)
    velocity = newVelocity
    if velocity > maxVelocity then
        velocity = maxVelocity
    elseif velocity < minVelocity then
        velocity = minVelocity
    end
    GUI.Val(slider, {velocity})
end

function accelerate() 
    isAccelerating = true
end

function stopAccelerate()
    isAccelerating = false
end

function brake()
    isBraking = true
end

function stopBrake()
    isBraking = false
end

function sliderChange(step)
    updateVelocity(tonumber(step))
    return step
end

function main()
    if isAccelerating then
        updateVelocity(velocity + 2)
    else
        if isBraking then
          velocity = velocity - 2
        end
        updateVelocity(velocity - 1)
    end
end

slider = GUI.New("Velocity", "Slider", {
    z = 11,
    x = 250,
    y = 30,
    w = 96,
    caption = "Velocity",
    min = minVelocity,
    max = maxVelocity,
    defaults = {0},
    inc = 1,
    dir = "h",
    font_a = 3,
    font_b = 4,
    col_txt = "txt",
    col_fill = "elm_fill",
    bg = "wnd_bg",
    show_handles = false,
    show_values = true,
    cap_x = 0,
    cap_y = 0,
    output = sliderChange
})

GUI.New("Accelerator", "Button", {
    z = 11,
    x = 310,
    y = 65,
    w = 60,
    h = 125,
    caption = "Accelerate",
    font = 3,
    col_txt = "txt",
    col_fill = "elm_frame",
    mouseup_handler = stopAccelerate,
    mousedown_handler = accelerate
})

GUI.New("Brake", "Button", {
    z = 11,
    x = 230,
    y = 65,
    w = 60,
    h = 125,
    caption = "Brake",
    font = 3,
    col_txt = "txt",
    col_fill = "elm_frame",
    mousedown_handler = brake,
    mouseup_handler = stopBrake
})

--[[GUI.New("Quit", "Button", {
    z = 11,
    x = 500,
    y = 15,
    w = 75,
    h = 30,
    caption = "Quit",
    font = 3,
    col_txt = "txt",
    col_fill = "elm_frame"
})]]--


GUI.Init()
GUI.func = main

GUI.freq = 0.1 -- GUI update frequency
GUI.Main()
